### ISSUE TITLE
Set up AWS account for all buttons

### ISSUE THREAD

**Issue by elizabethbarr** [elizabethbarr/pressbev#17]
Credentials here, please:

**Comment by chucklapress** [comment]
Wednesday ETA for arrival of sample buttons

**Comment by elizabethbarr** [comment]
One account should be able to handle lots of buttons, yes?

**Comment by elizabethbarr** [comment]
Use this AWS account from now on for Bev biz:
eliz@pressbev.com
pwd: davemb
Account ID: 258687550065
