### ISSUE TITLE
Configure first two buttons/Put results in Google doc

### ISSUE THREAD

**Issue by elizabethbarr** [elizabethbarr/pressbev#18]
Experiment with integrations. Keep notes in a Google doc for all to share. 
Link to Google doc here:

**Comment by chucklapress** [comment]
Some ideas, will begin google doc if needed would be helpful if you set format and shair or at least till me what form of format you would like the doc in.

**Comment by chucklapress** [comment]
They'll be here today and thats Wednesday openworks work

**Comment by chucklapress** [comment]
Shiz thought it had me licked, but guess again.... fork it baby
