### ISSUE TITLE
Build dashboard

### ISSUE THREAD

**Issue by elizabethbarr** [elizabethbarr/pressbev#3]
Build the awesome Bev dashboard showing all of our clients, their contact info, their buttons' Amazon numbers, and other info.

**Comment by chucklapress** [comment]
How about you give me a damn minute to learn this stuff, OK?

**Comment by chucklapress** [comment]
Will be beginning dashboard as a django project tomorrow am, I will notify status and repo location after first commit.

**Comment by elizabethbarr** [comment]
Dashboard needs to track the following:

Restaurant name (will be primary identifier of account)
Harvest client number
Client name
email
Phone number (if possible, both cell and business phone)
Restaurant address
Serial numbers of buttons
   • For each serial number: type of press (1, 2, or 3); description of integration (what it does); and GitHub repo for that integration (Will utilize this naming convention: Harvest client number, Amazon serial number, number of press. Eg., 123_456789_1; 123_456789_2; 123_456789_3)
Total initial invoice amount 
Monthly subscription amount
Shipping tracking number

**Comment by chucklapress** [comment]
May need a couple of minor polish items but I'm thinking put a fork in it

**Comment by elizabethbarr** [comment]
You rock, sir. 

Definitely want to be able to include link to GitHub repo for each button press.
